openapi: 3.0.3
info:
  version: "1.0"
  contact:
    email: support@signoz.io
    name: SigNoz Support
    url: https://signoz.io
  description: OpenTelemetry-Native Logs, Metrics and Traces in a single pane
  termsOfService: https://signoz.io/terms-of-service/
  title: SigNoz alerts zeus API
servers:
- description: The fully qualified URL to the SigNoz APIServer.
  url: https://{host}:{port}{base_path}
  variables:
    base_path:
      default: /
      description: The base path of the SigNoz APIServer
    host:
      default: localhost
      description: The host of the SigNoz APIServer
    port:
      default: '8080'
      description: The port of the SigNoz APIServer
tags:
- name: zeus
paths:
  /api/v2/zeus/hosts:
    get:
      deprecated: false
      description: This endpoint gets the host info from zeus.
      operationId: GetHosts
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/ZeustypesGettableHost'
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      security:
      - api_key:
        - VIEWER
      - tokenizer:
        - VIEWER
      summary: Get host info from Zeus.
      tags:
      - zeus
    put:
      deprecated: false
      description: This endpoint saves the host of a deployment to zeus.
      operationId: PutHost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ZeustypesPostableHost'
      responses:
        '204':
          description: No Content
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Not Found
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Conflict
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      security:
      - api_key:
        - ADMIN
      - tokenizer:
        - ADMIN
      summary: Put host in Zeus for a deployment.
      tags:
      - zeus
  /api/v2/zeus/profiles:
    put:
      deprecated: false
      description: This endpoint saves the profile of a deployment to zeus.
      operationId: PutProfile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ZeustypesPostableProfile'
      responses:
        '204':
          description: No Content
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Not Found
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Conflict
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      security:
      - api_key:
        - ADMIN
      - tokenizer:
        - ADMIN
      summary: Put profile in Zeus for a deployment.
      tags:
      - zeus
components:
  schemas:
    ZeustypesPostableHost:
      properties:
        name:
          type: string
      required:
      - name
      type: object
    RenderErrorResponse:
      properties:
        error:
          $ref: '#/components/schemas/ErrorsJSON'
        status:
          type: string
      required:
      - status
      - error
      type: object
    ErrorsJSON:
      properties:
        code:
          type: string
        errors:
          items:
            $ref: '#/components/schemas/ErrorsResponseerroradditional'
          type: array
        message:
          type: string
        url:
          type: string
      required:
      - code
      - message
      type: object
    ErrorsResponseerroradditional:
      properties:
        message:
          type: string
      type: object
    ZeustypesHost:
      properties:
        is_default:
          type: boolean
        name:
          type: string
        url:
          type: string
      required:
      - name
      - is_default
      - url
      type: object
    ZeustypesPostableProfile:
      properties:
        existing_observability_tool:
          type: string
        has_existing_observability_tool:
          type: boolean
        logs_scale_per_day_in_gb:
          format: int64
          type: integer
        number_of_hosts:
          format: int64
          type: integer
        number_of_services:
          format: int64
          type: integer
        reasons_for_interest_in_signoz:
          items:
            type: string
          nullable: true
          type: array
        timeline_for_migrating_to_signoz:
          type: string
        uses_otel:
          type: boolean
        where_did_you_discover_signoz:
          type: string
      required:
      - uses_otel
      - has_existing_observability_tool
      - existing_observability_tool
      - reasons_for_interest_in_signoz
      - logs_scale_per_day_in_gb
      - number_of_services
      - number_of_hosts
      - where_did_you_discover_signoz
      - timeline_for_migrating_to_signoz
      type: object
    ZeustypesGettableHost:
      properties:
        hosts:
          items:
            $ref: '#/components/schemas/ZeustypesHost'
          nullable: true
          type: array
        name:
          type: string
        state:
          type: string
        tier:
          type: string
      required:
      - name
      - state
      - tier
      - hosts
      type: object
  securitySchemes:
    api_key:
      description: API Keys
      in: header
      name: SigNoz-Api-Key
      type: apiKey
    tokenizer:
      bearerFormat: Tokenizer
      description: Tokens generated by the tokenizer
      scheme: bearer
      type: http
