openapi: 3.0.3
info:
  version: "1.0"
  contact:
    email: support@signoz.io
    name: SigNoz Support
    url: https://signoz.io
  description: OpenTelemetry-Native Logs, Metrics and Traces in a single pane
  termsOfService: https://signoz.io/terms-of-service/
  title: SigNoz alerts authz API
servers:
- description: The fully qualified URL to the SigNoz APIServer.
  url: https://{host}:{port}{base_path}
  variables:
    base_path:
      default: /
      description: The base path of the SigNoz APIServer
    host:
      default: localhost
      description: The host of the SigNoz APIServer
    port:
      default: '8080'
      description: The port of the SigNoz APIServer
tags:
- name: authz
paths:
  /api/v1/authz/check:
    post:
      deprecated: false
      description: Checks if the authenticated user has permissions for given transactions
      operationId: AuthzCheck
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/AuthtypesTransaction'
              type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/AuthtypesGettableTransaction'
                    type: array
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: OK
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      summary: Check permissions
      tags:
      - authz
  /api/v1/authz/resources:
    get:
      deprecated: false
      description: Gets all the available resources
      operationId: AuthzResources
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/AuthtypesGettableResources'
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: OK
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      summary: Get resources
      tags:
      - authz
components:
  schemas:
    AuthtypesTransaction:
      properties:
        object:
          $ref: '#/components/schemas/AuthtypesObject'
        relation:
          type: string
      required:
      - relation
      - object
      type: object
    RenderErrorResponse:
      properties:
        error:
          $ref: '#/components/schemas/ErrorsJSON'
        status:
          type: string
      required:
      - status
      - error
      type: object
    AuthtypesGettableTransaction:
      properties:
        authorized:
          type: boolean
        object:
          $ref: '#/components/schemas/AuthtypesObject'
        relation:
          type: string
      required:
      - relation
      - object
      - authorized
      type: object
    AuthtypesObject:
      properties:
        resource:
          $ref: '#/components/schemas/AuthtypesResource'
        selector:
          type: string
      required:
      - resource
      - selector
      type: object
    AuthtypesResource:
      properties:
        name:
          type: string
        type:
          type: string
      required:
      - name
      - type
      type: object
    ErrorsJSON:
      properties:
        code:
          type: string
        errors:
          items:
            $ref: '#/components/schemas/ErrorsResponseerroradditional'
          type: array
        message:
          type: string
        url:
          type: string
      required:
      - code
      - message
      type: object
    ErrorsResponseerroradditional:
      properties:
        message:
          type: string
      type: object
    AuthtypesGettableResources:
      properties:
        relations:
          additionalProperties:
            items:
              type: string
            type: array
          nullable: true
          type: object
        resources:
          items:
            $ref: '#/components/schemas/AuthtypesResource'
          type: array
      required:
      - resources
      - relations
      type: object
  securitySchemes:
    api_key:
      description: API Keys
      in: header
      name: SigNoz-Api-Key
      type: apiKey
    tokenizer:
      bearerFormat: Tokenizer
      description: Tokens generated by the tokenizer
      scheme: bearer
      type: http
