openapi: 3.0.3
info:
  version: "1.0"
  contact:
    email: support@signoz.io
    name: SigNoz Support
    url: https://signoz.io
  description: OpenTelemetry-Native Logs, Metrics and Traces in a single pane
  termsOfService: https://signoz.io/terms-of-service/
  title: SigNoz alerts fields API
servers:
- description: The fully qualified URL to the SigNoz APIServer.
  url: https://{host}:{port}{base_path}
  variables:
    base_path:
      default: /
      description: The base path of the SigNoz APIServer
    host:
      default: localhost
      description: The host of the SigNoz APIServer
    port:
      default: '8080'
      description: The port of the SigNoz APIServer
tags:
- name: fields
paths:
  /api/v1/fields/keys:
    get:
      deprecated: false
      description: This endpoint returns field keys
      operationId: GetFieldsKeys
      parameters:
      - in: query
        name: signal
        schema:
          $ref: '#/components/schemas/TelemetrytypesSignal'
      - in: query
        name: source
        schema:
          $ref: '#/components/schemas/TelemetrytypesSource'
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: startUnixMilli
        schema:
          format: int64
          type: integer
      - in: query
        name: endUnixMilli
        schema:
          format: int64
          type: integer
      - in: query
        name: fieldContext
        schema:
          $ref: '#/components/schemas/TelemetrytypesFieldContext'
      - in: query
        name: fieldDataType
        schema:
          $ref: '#/components/schemas/TelemetrytypesFieldDataType'
      - in: query
        name: metricName
        schema:
          type: string
      - in: query
        name: metricNamespace
        schema:
          type: string
      - in: query
        name: searchText
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/TelemetrytypesGettableFieldKeys'
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: OK
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      security:
      - api_key:
        - VIEWER
      - tokenizer:
        - VIEWER
      summary: Get field keys
      tags:
      - fields
  /api/v1/fields/values:
    get:
      deprecated: false
      description: This endpoint returns field values
      operationId: GetFieldsValues
      parameters:
      - in: query
        name: signal
        schema:
          $ref: '#/components/schemas/TelemetrytypesSignal'
      - in: query
        name: source
        schema:
          $ref: '#/components/schemas/TelemetrytypesSource'
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: startUnixMilli
        schema:
          format: int64
          type: integer
      - in: query
        name: endUnixMilli
        schema:
          format: int64
          type: integer
      - in: query
        name: fieldContext
        schema:
          $ref: '#/components/schemas/TelemetrytypesFieldContext'
      - in: query
        name: fieldDataType
        schema:
          $ref: '#/components/schemas/TelemetrytypesFieldDataType'
      - in: query
        name: metricName
        schema:
          type: string
      - in: query
        name: metricNamespace
        schema:
          type: string
      - in: query
        name: searchText
        schema:
          type: string
      - in: query
        name: name
        schema:
          type: string
      - in: query
        name: existingQuery
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/TelemetrytypesGettableFieldValues'
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: OK
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      security:
      - api_key:
        - VIEWER
      - tokenizer:
        - VIEWER
      summary: Get field values
      tags:
      - fields
components:
  schemas:
    TelemetrytypesGettableFieldKeys:
      properties:
        complete:
          type: boolean
        keys:
          additionalProperties:
            items:
              $ref: '#/components/schemas/TelemetrytypesTelemetryFieldKey'
            type: array
          nullable: true
          type: object
      required:
      - keys
      - complete
      type: object
    TelemetrytypesFieldDataType:
      enum:
      - string
      - bool
      - float64
      - int64
      - number
      type: string
    RenderErrorResponse:
      properties:
        error:
          $ref: '#/components/schemas/ErrorsJSON'
        status:
          type: string
      required:
      - status
      - error
      type: object
    TelemetrytypesTelemetryFieldKey:
      properties:
        description:
          type: string
        fieldContext:
          $ref: '#/components/schemas/TelemetrytypesFieldContext'
        fieldDataType:
          $ref: '#/components/schemas/TelemetrytypesFieldDataType'
        name:
          type: string
        signal:
          $ref: '#/components/schemas/TelemetrytypesSignal'
        unit:
          type: string
      required:
      - name
      type: object
    TelemetrytypesSource:
      enum:
      - meter
      type: string
    ErrorsJSON:
      properties:
        code:
          type: string
        errors:
          items:
            $ref: '#/components/schemas/ErrorsResponseerroradditional'
          type: array
        message:
          type: string
        url:
          type: string
      required:
      - code
      - message
      type: object
    TelemetrytypesTelemetryFieldValues:
      properties:
        boolValues:
          items:
            type: boolean
          type: array
        numberValues:
          items:
            format: double
            type: number
          type: array
        relatedValues:
          items:
            type: string
          type: array
        stringValues:
          items:
            type: string
          type: array
      type: object
    ErrorsResponseerroradditional:
      properties:
        message:
          type: string
      type: object
    TelemetrytypesSignal:
      enum:
      - traces
      - logs
      - metrics
      type: string
    TelemetrytypesFieldContext:
      enum:
      - metric
      - log
      - span
      - resource
      - attribute
      - body
      type: string
    TelemetrytypesGettableFieldValues:
      properties:
        complete:
          type: boolean
        values:
          $ref: '#/components/schemas/TelemetrytypesTelemetryFieldValues'
      required:
      - values
      - complete
      type: object
  securitySchemes:
    api_key:
      description: API Keys
      in: header
      name: SigNoz-Api-Key
      type: apiKey
    tokenizer:
      bearerFormat: Tokenizer
      description: Tokens generated by the tokenizer
      scheme: bearer
      type: http
