openapi: 3.0.3
info:
  contact:
    email: support@signoz.io
    name: SigNoz Support
    url: https://signoz.io
  description: OpenTelemetry-Native Logs, Metrics and Traces in a single pane
  termsOfService: https://signoz.io/terms-of-service/
  title: SigNoz alerts downtimeschedules API
  version: ''
servers:
- description: The fully qualified URL to the SigNoz APIServer.
  url: https://{host}:{port}{base_path}
  variables:
    base_path:
      default: /
      description: The base path of the SigNoz APIServer
    host:
      default: localhost
      description: The host of the SigNoz APIServer
    port:
      default: '8080'
      description: The port of the SigNoz APIServer
tags:
- name: downtimeschedules
paths:
  /api/v1/downtime_schedules:
    get:
      deprecated: false
      description: This endpoint lists all planned maintenance / downtime schedules
      operationId: ListDowntimeSchedules
      parameters:
      - in: query
        name: active
        schema:
          nullable: true
          type: boolean
      - in: query
        name: recurring
        schema:
          nullable: true
          type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/RuletypesPlannedMaintenance'
                    type: array
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: OK
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      security:
      - api_key:
        - VIEWER
      - tokenizer:
        - VIEWER
      summary: List downtime schedules
      tags:
      - downtimeschedules
    post:
      deprecated: false
      description: This endpoint creates a new planned maintenance / downtime schedule
      operationId: CreateDowntimeSchedule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RuletypesPostablePlannedMaintenance'
      responses:
        '201':
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/RuletypesPlannedMaintenance'
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: Created
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      security:
      - api_key:
        - EDITOR
      - tokenizer:
        - EDITOR
      summary: Create downtime schedule
      tags:
      - downtimeschedules
  /api/v1/downtime_schedules/{id}:
    delete:
      deprecated: false
      description: This endpoint deletes a downtime schedule by ID
      operationId: DeleteDowntimeScheduleByID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      security:
      - api_key:
        - EDITOR
      - tokenizer:
        - EDITOR
      summary: Delete downtime schedule
      tags:
      - downtimeschedules
    get:
      deprecated: false
      description: This endpoint returns a downtime schedule by ID
      operationId: GetDowntimeScheduleByID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/RuletypesPlannedMaintenance'
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: OK
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      security:
      - api_key:
        - VIEWER
      - tokenizer:
        - VIEWER
      summary: Get downtime schedule by ID
      tags:
      - downtimeschedules
    put:
      deprecated: false
      description: This endpoint updates a downtime schedule by ID
      operationId: UpdateDowntimeScheduleByID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RuletypesPostablePlannedMaintenance'
      responses:
        '204':
          description: No Content
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      security:
      - api_key:
        - EDITOR
      - tokenizer:
        - EDITOR
      summary: Update downtime schedule
      tags:
      - downtimeschedules
components:
  schemas:
    RuletypesSchedule:
      properties:
        endTime:
          format: date-time
          type: string
        recurrence:
          $ref: '#/components/schemas/RuletypesRecurrence'
        startTime:
          format: date-time
          type: string
        timezone:
          type: string
      required:
      - timezone
      type: object
    RuletypesPostablePlannedMaintenance:
      properties:
        alertIds:
          items:
            type: string
          nullable: true
          type: array
        description:
          type: string
        name:
          type: string
        schedule:
          $ref: '#/components/schemas/RuletypesSchedule'
      required:
      - name
      - schedule
      type: object
    RenderErrorResponse:
      properties:
        error:
          $ref: '#/components/schemas/ErrorsJSON'
        status:
          type: string
      required:
      - status
      - error
      type: object
    ErrorsJSON:
      properties:
        code:
          type: string
        errors:
          items:
            $ref: '#/components/schemas/ErrorsResponseerroradditional'
          type: array
        message:
          type: string
        url:
          type: string
      required:
      - code
      - message
      type: object
    RuletypesMaintenanceStatus:
      enum:
      - active
      - upcoming
      - expired
      type: string
    ErrorsResponseerroradditional:
      properties:
        message:
          type: string
      type: object
    RuletypesRepeatType:
      enum:
      - daily
      - weekly
      - monthly
      type: string
    RuletypesRecurrence:
      properties:
        duration:
          type: string
        endTime:
          format: date-time
          nullable: true
          type: string
        repeatOn:
          items:
            $ref: '#/components/schemas/RuletypesRepeatOn'
          nullable: true
          type: array
        repeatType:
          $ref: '#/components/schemas/RuletypesRepeatType'
        startTime:
          format: date-time
          type: string
      required:
      - startTime
      - duration
      - repeatType
      type: object
    RuletypesMaintenanceKind:
      enum:
      - fixed
      - recurring
      type: string
    RuletypesPlannedMaintenance:
      properties:
        alertIds:
          items:
            type: string
          nullable: true
          type: array
        createdAt:
          format: date-time
          type: string
        createdBy:
          type: string
        description:
          type: string
        id:
          type: string
        kind:
          $ref: '#/components/schemas/RuletypesMaintenanceKind'
        name:
          type: string
        schedule:
          $ref: '#/components/schemas/RuletypesSchedule'
        status:
          $ref: '#/components/schemas/RuletypesMaintenanceStatus'
        updatedAt:
          format: date-time
          type: string
        updatedBy:
          type: string
      required:
      - id
      - name
      - schedule
      - status
      - kind
      type: object
    RuletypesRepeatOn:
      enum:
      - sunday
      - monday
      - tuesday
      - wednesday
      - thursday
      - friday
      - saturday
      type: string
  securitySchemes:
    api_key:
      description: API Keys
      in: header
      name: SigNoz-Api-Key
      type: apiKey
    tokenizer:
      bearerFormat: Tokenizer
      description: Tokens generated by the tokenizer
      scheme: bearer
      type: http
