openapi: 3.0.3
info:
  version: "1.0"
  contact:
    email: support@signoz.io
    name: SigNoz Support
    url: https://signoz.io
  description: OpenTelemetry-Native Logs, Metrics and Traces in a single pane
  termsOfService: https://signoz.io/terms-of-service/
  title: SigNoz alerts health API
servers:
- description: The fully qualified URL to the SigNoz APIServer.
  url: https://{host}:{port}{base_path}
  variables:
    base_path:
      default: /
      description: The base path of the SigNoz APIServer
    host:
      default: localhost
      description: The host of the SigNoz APIServer
    port:
      default: '8080'
      description: The port of the SigNoz APIServer
tags:
- name: health
paths:
  /api/v2/healthz:
    get:
      operationId: Healthz
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/FactoryResponse'
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: OK
        '503':
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/FactoryResponse'
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: Service Unavailable
      summary: Health check
      tags:
      - health
  /api/v2/livez:
    get:
      deprecated: false
      description: ''
      operationId: Livez
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/FactoryResponse'
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: OK
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      summary: Liveness check
      tags:
      - health
  /api/v2/readyz:
    get:
      operationId: Readyz
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/FactoryResponse'
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: OK
        '503':
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/FactoryResponse'
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: Service Unavailable
      summary: Readiness check
      tags:
      - health
components:
  schemas:
    ErrorsJSON:
      properties:
        code:
          type: string
        errors:
          items:
            $ref: '#/components/schemas/ErrorsResponseerroradditional'
          type: array
        message:
          type: string
        url:
          type: string
      required:
      - code
      - message
      type: object
    RenderErrorResponse:
      properties:
        error:
          $ref: '#/components/schemas/ErrorsJSON'
        status:
          type: string
      required:
      - status
      - error
      type: object
    FactoryResponse:
      properties:
        healthy:
          type: boolean
        services:
          additionalProperties:
            items:
              type: string
            type: array
          nullable: true
          type: object
      type: object
    ErrorsResponseerroradditional:
      properties:
        message:
          type: string
      type: object
  securitySchemes:
    api_key:
      description: API Keys
      in: header
      name: SigNoz-Api-Key
      type: apiKey
    tokenizer:
      bearerFormat: Tokenizer
      description: Tokens generated by the tokenizer
      scheme: bearer
      type: http
