openapi: 3.0.3
info:
  version: "1.0"
  contact:
    email: support@signoz.io
    name: SigNoz Support
    url: https://signoz.io
  description: OpenTelemetry-Native Logs, Metrics and Traces in a single pane
  termsOfService: https://signoz.io/terms-of-service/
  title: SigNoz alerts global API
servers:
- description: The fully qualified URL to the SigNoz APIServer.
  url: https://{host}:{port}{base_path}
  variables:
    base_path:
      default: /
      description: The base path of the SigNoz APIServer
    host:
      default: localhost
      description: The host of the SigNoz APIServer
    port:
      default: '8080'
      description: The port of the SigNoz APIServer
tags:
- name: global
paths:
  /api/v1/global/config:
    get:
      deprecated: false
      description: This endpoint returns global config
      operationId: GetGlobalConfig
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/GlobaltypesConfig'
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: OK
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      summary: Get global config
      tags:
      - global
components:
  schemas:
    GlobaltypesAPIKeyConfig:
      properties:
        enabled:
          type: boolean
      type: object
    GlobaltypesImpersonationConfig:
      properties:
        enabled:
          type: boolean
      type: object
    RenderErrorResponse:
      properties:
        error:
          $ref: '#/components/schemas/ErrorsJSON'
        status:
          type: string
      required:
      - status
      - error
      type: object
    GlobaltypesTokenizerConfig:
      properties:
        enabled:
          type: boolean
      type: object
    ErrorsJSON:
      properties:
        code:
          type: string
        errors:
          items:
            $ref: '#/components/schemas/ErrorsResponseerroradditional'
          type: array
        message:
          type: string
        url:
          type: string
      required:
      - code
      - message
      type: object
    ErrorsResponseerroradditional:
      properties:
        message:
          type: string
      type: object
    GlobaltypesIdentNConfig:
      properties:
        apikey:
          $ref: '#/components/schemas/GlobaltypesAPIKeyConfig'
        impersonation:
          $ref: '#/components/schemas/GlobaltypesImpersonationConfig'
        tokenizer:
          $ref: '#/components/schemas/GlobaltypesTokenizerConfig'
      type: object
    GlobaltypesConfig:
      properties:
        external_url:
          type: string
        identN:
          $ref: '#/components/schemas/GlobaltypesIdentNConfig'
        ingestion_url:
          type: string
        mcp_url:
          nullable: true
          type: string
      required:
      - external_url
      - ingestion_url
      - mcp_url
      type: object
  securitySchemes:
    api_key:
      description: API Keys
      in: header
      name: SigNoz-Api-Key
      type: apiKey
    tokenizer:
      bearerFormat: Tokenizer
      description: Tokens generated by the tokenizer
      scheme: bearer
      type: http
