openapi: 3.0.3
info:
  contact:
    email: support@signoz.io
    name: SigNoz Support
    url: https://signoz.io
  description: OpenTelemetry-Native Logs, Metrics and Traces in a single pane
  termsOfService: https://signoz.io/terms-of-service/
  title: SigNoz alerts tracedetail API
  version: ''
servers:
- description: The fully qualified URL to the SigNoz APIServer.
  url: https://{host}:{port}{base_path}
  variables:
    base_path:
      default: /
      description: The base path of the SigNoz APIServer
    host:
      default: localhost
      description: The host of the SigNoz APIServer
    port:
      default: '8080'
      description: The port of the SigNoz APIServer
tags:
- name: tracedetail
paths:
  /api/v3/traces/{traceID}/waterfall:
    post:
      deprecated: false
      description: Returns the waterfall view of spans for a given trace ID with tree structure, metadata, and windowed pagination
      operationId: GetWaterfall
      parameters:
      - in: path
        name: traceID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TracedetailtypesPostableWaterfall'
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: '#/components/schemas/TracedetailtypesGettableWaterfallTrace'
                  status:
                    type: string
                required:
                - status
                - data
                type: object
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderErrorResponse'
          description: Internal Server Error
      security:
      - api_key:
        - VIEWER
      - tokenizer:
        - VIEWER
      summary: Get waterfall view for a trace
      tags:
      - tracedetail
components:
  schemas:
    TracedetailtypesSpanAggregationResult:
      properties:
        aggregation:
          $ref: '#/components/schemas/TracedetailtypesSpanAggregationType'
        field:
          $ref: '#/components/schemas/TelemetrytypesTelemetryFieldKey'
        value:
          additionalProperties:
            minimum: 0
            type: integer
          nullable: true
          type: object
      type: object
    TelemetrytypesFieldDataType:
      enum:
      - string
      - bool
      - float64
      - int64
      - number
      type: string
    RenderErrorResponse:
      properties:
        error:
          $ref: '#/components/schemas/ErrorsJSON'
        status:
          type: string
      required:
      - status
      - error
      type: object
    TelemetrytypesTelemetryFieldKey:
      properties:
        description:
          type: string
        fieldContext:
          $ref: '#/components/schemas/TelemetrytypesFieldContext'
        fieldDataType:
          $ref: '#/components/schemas/TelemetrytypesFieldDataType'
        name:
          type: string
        signal:
          $ref: '#/components/schemas/TelemetrytypesSignal'
        unit:
          type: string
      required:
      - name
      type: object
    TracedetailtypesEvent:
      properties:
        attributeMap:
          additionalProperties: {}
          type: object
        isError:
          type: boolean
        name:
          type: string
        timeUnixNano:
          minimum: 0
          type: integer
      type: object
    ErrorsJSON:
      properties:
        code:
          type: string
        errors:
          items:
            $ref: '#/components/schemas/ErrorsResponseerroradditional'
          type: array
        message:
          type: string
        url:
          type: string
      required:
      - code
      - message
      type: object
    TracedetailtypesWaterfallSpan:
      properties:
        attributes:
          additionalProperties: {}
          nullable: true
          type: object
        db_name:
          type: string
        db_operation:
          type: string
        duration_nano:
          minimum: 0
          type: integer
        events:
          items:
            $ref: '#/components/schemas/TracedetailtypesEvent'
          nullable: true
          type: array
        external_http_method:
          type: string
        external_http_url:
          type: string
        flags:
          minimum: 0
          type: integer
        has_children:
          type: boolean
        has_error:
          type: boolean
        http_host:
          type: string
        http_method:
          type: string
        http_url:
          type: string
        is_remote:
          type: string
        kind_string:
          type: string
        level:
          minimum: 0
          type: integer
        name:
          type: string
        parent_span_id:
          type: string
        resource:
          additionalProperties:
            type: string
          nullable: true
          type: object
        response_status_code:
          type: string
        span_id:
          type: string
        status_code:
          type: integer
        status_code_string:
          type: string
        status_message:
          type: string
        sub_tree_node_count:
          minimum: 0
          type: integer
        trace_id:
          type: string
        trace_state:
          type: string
      type: object
    ErrorsResponseerroradditional:
      properties:
        message:
          type: string
      type: object
    TracedetailtypesGettableWaterfallTrace:
      properties:
        aggregations:
          items:
            $ref: '#/components/schemas/TracedetailtypesSpanAggregationResult'
          nullable: true
          type: array
        endTimestampMillis:
          minimum: 0
          type: integer
        hasMissingSpans:
          type: boolean
        hasMore:
          type: boolean
        rootServiceEntryPoint:
          type: string
        rootServiceName:
          type: string
        serviceNameToTotalDurationMap:
          additionalProperties:
            minimum: 0
            type: integer
          nullable: true
          type: object
        spans:
          items:
            $ref: '#/components/schemas/TracedetailtypesWaterfallSpan'
          nullable: true
          type: array
        startTimestampMillis:
          minimum: 0
          type: integer
        totalErrorSpansCount:
          minimum: 0
          type: integer
        totalSpansCount:
          minimum: 0
          type: integer
        uncollapsedSpans:
          items:
            type: string
          nullable: true
          type: array
      type: object
    TelemetrytypesSignal:
      enum:
      - traces
      - logs
      - metrics
      type: string
    TelemetrytypesFieldContext:
      enum:
      - metric
      - log
      - span
      - resource
      - attribute
      - body
      type: string
    TracedetailtypesPostableWaterfall:
      properties:
        aggregations:
          items:
            $ref: '#/components/schemas/TracedetailtypesSpanAggregation'
          nullable: true
          type: array
        limit:
          minimum: 0
          type: integer
        selectedSpanId:
          type: string
        uncollapsedSpans:
          items:
            type: string
          nullable: true
          type: array
      type: object
    TracedetailtypesSpanAggregationType:
      enum:
      - span_count
      - execution_time_percentage
      - duration
      type: string
    TracedetailtypesSpanAggregation:
      properties:
        aggregation:
          $ref: '#/components/schemas/TracedetailtypesSpanAggregationType'
        field:
          $ref: '#/components/schemas/TelemetrytypesTelemetryFieldKey'
      type: object
  securitySchemes:
    api_key:
      description: API Keys
      in: header
      name: SigNoz-Api-Key
      type: apiKey
    tokenizer:
      bearerFormat: Tokenizer
      description: Tokens generated by the tokenizer
      scheme: bearer
      type: http
